blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/tomazb/change-site/discussions
    about: Ask questions, share ideas, and discuss with the community
  - name: Security Issues
    url: https://github.com/tomazb/change-site/security/advisories
    about: Report security vulnerabilities privately